[profile.default]
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "ipfs"
optimizer_runs = 1_000_000
libs = ['lib']
remappings = [
    "amm-core/=lib/amm-core/src/"
]
match_path = "test/unit/*.sol"
block_base_fee_per_gas = 10_000_000  # set to arbitrum's base fee of 0.01 gwei
verbosity = 3
fs_permissions = [
    { access = "read", path = "./out" }
]
ignored_error_codes = []
skip = ["test/large/*.sol"]

[profile.default.fuzz]
seed = "0xe9cdc8fb2a2c0d1c046034d74d6498826ae3f1d9877353cf40d8a6a7aedfe875"

[profile.large-test]
via_ir = true
match_path = "test/large/*.sol"
match_test = "testGetQuote_RandomizeAllParam_3HopRoute"
skip = []

[profile.integration]
match_path = "test/integration/*.sol"

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000
