[profile.default]
via_ir = true
solc = "0.8.26"
bytecode_hash = "ipfs"
optimizer_runs = 1_000_000
libs = ['lib']
remappings = [
    "amm-core/=lib/amm-core/src/"
]
match_path = "test/unit/*.sol"
block_base_fee_per_gas = 10_000_000  # set to arbitrum's base fee of 0.01 gwei
verbosity = 3
fs_permissions = [
    { access = "read", path = "./out" }
]
ignored_error_codes = []

[profile.integration]
match_path = "test/integration/*.sol"

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000
